name: forminator
description: Forminator simplifies form management and validation in Flutter with customizable fields, dynamic error handling, and batch validation, optimizing form creation with advanced features.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
